MODEL:
  TYPE: vrwkv7
  NAME: vrwkv7_tiny_0230s
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 320
    DEPTHS: [ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2 ]
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 1.0
    SSM_CONV: 3
    SSM_CONV_BIAS: false
    SSM_FORWARDTYPE: "v05_noz" # v3_noz
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v2"
    NORM_LAYER: "ln2d"
TRAIN:
  BASE_LR: 4e-4
  MIN_LR: 2e-5
  WARMUP_LR: 2e-5
  WARMUP_EPOCHS: 1
